site_name: The Hacking Handbook
site_description: The encyclopedia for offensive security in the cloud.
site_url: https://0xeval.github.io/

docs_dir: content

theme:
  name: material
#  logo: images/logo.png
#  favicon: images/logo.png
#  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant  # ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
    - navigation.indexes
    - navigation.tracking
    - navigation.sections # ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#with-sections
#   - navigation.tabs
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/lightbulb
        name: Switch to Dark Mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to Light Mode

markdown_extensions:
  - admonition
#  - meta
#  - attr_list
#  - md_in_html
#  - pymdownx.details
#  - pymdownx.superfences
#  - pymdownx.emoji:
#      emoji_index: !!python/name:materialx.emoji.twemoji
#      emoji_generator: !!python/name:materialx.emoji.to_svg

#plugins:
#  - search
#  - rss: # non-standard
#      length: 200
#  - awesome-pages # non-standard
#  - minify:
#      minify_html: true
#      minify_js: true
#      minify_css: true

repo_url: https://github.com/0xEval/0xeval.github.io
repo_name: 0xeval/hackinghandbook

extra:
  social:
#    - icon: fontawesome/brands/mastodon
#      link: https://infosec.exchange/@hackingthecloud
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/0xEval
#    - icon: fontawesome/brands/linkedin
#      link: https://www.linkedin.com/in/nick-frichette/
    - icon: fontawesome/brands/github
      link: https://github.com/0xEval/0xeval.github.io
